# Generated by Django 2.2.3 on 2019-07-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaunchPad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lp_id', models.IntegerField()),
                ('lp_name', models.CharField(max_length=255)),
                ('lp_status', models.CharField(max_length=10)),
            ],
        ),
    ]
